### ISSUE TITLE
ios does not work

### ISSUE THREAD

**Issue by landabaso** [maksimlya/react-native-fast-text-encoder#1]
Hey! Nice work!

I tried to use this package but I believe iOS has some subtle bugs which makes it impossible to work.
I guess most of the problems come simply from the naming conversion with OpenPGP. I renamed some files / strings but could not get very far.
Please let me know if you have some more complete version for iOS. Thanks!

**Comment by maksimlya** [comment]
Hi, iOS should be fixed now, v0.1.9. I did not test it for performance tho, so please let me know how that works.

**Comment by landabaso** [comment]
Thanks for updating it!
However, I think I just hit this issue (I'm on a M2 Mac): https://github.com/jerson/react-native-fast-openpgp/issues/100

**Comment by maksimlya** [comment]
I don't have m1/m2 unfortunately to make it optimal
. There's few options:
- Run app inside rosetta emulator
- I can provide you build with arm64 build for simulator, in this case tho app probably wont run on device(as I cant bundle 2 arm64 builds into same lib)
- Debug/run on real device. All new iphone devices should work fine.

I'll check if I can create dynamic libs, but that is nit likely to be soon.

**Comment by maksimlya** [comment]
Added compiled libs for simulator arm64 in 1f8751665adc917e73ed7baf3b4beff1ea87ae4c, published under `react-native-fast-encoder@0.1.9-arm`

**Comment by landabaso** [comment]
Thanks a ton for your work @maksimlya ! I'll test it during the weekend and report you back.

**Comment by landabaso** [comment]
Hi @maksimlya,

Thank you for the updates. I've tried integrating the latest changes but am still encountering issues. Here’s what I found and tried:

The installed package version is:
```json
"react-native-fast-encoder": "^0.1.9-arm",
```

I updated the `podspec` to include `arm64` as a valid architecture for the iOS simulator, with the following configurations:
```ruby
s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64 arm64', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => '' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => '' }
```

Despite these changes, I still receive the following errors when linking:
```
› Linking
❌  ld: in /Users/xxxxx/node_modules/react-native-fast-encoder/ios/libencoder_bridge.a(go.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/xxxxx/node_modules/react-native-fast-encoder/ios/libencoder_bridge.a' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
› 2 error(s), and 0 warning(s)
CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
```

Here is the architecture info for the library:
```
lipo -info node_modules/react-native-fast-encoder/ios/libencoder_bridge.a
Architectures in the fat file: node_modules/react-native-fast-encoder/ios/libencoder_bridge.a are: arm64
```

It appears the library is compiled for arm64 devices but not configured for the iOS Simulator on Apple Silicon Macs. Could you guide me on how to correctly integrate it or if there are additional steps I should take?

Thank you for your assistance.

**Comment by landabaso** [comment]
Hi again @maksimlya,

I wanted to share that your library performs exceptionally well on actual devices—it's super fast! Great work! However, I'm encountering the mentioned challenges during the development phase, particularly when using the iOS Simulator on Apple Silicon Macs.

Hermes engine in React Native recently added support for TextEncoder (but not TextDecoder - which is really needed) as seen here:
[https://github.com/facebook/hermes/issues/948](https://github.com/facebook/hermes/issues/948)

Given this, I believe your library is uniquely positioned in this field and could see increased usage as these tiny details are polished.

Could you consider providing a universal binary or an XCFramework that supports both simulator (x86_64 and arm64 for simulators on Intel and Apple Silicon Macs) and real device (arm64) architectures? This solution would greatly simplify the development process and ensure compatibility across all platforms.

Thank you for your efforts! I am looking forward to your suggestions.

**Comment by landabaso** [comment]
Hi @maksimlya,

I just noticed you released version 0.1.11—thank you so much!

I've tested it on Android and iOS simulators (on an M2 Mac) as well as on real Android and iOS devices, and it works wonderfully. It’s super fast!

I did encounter a minor issue with the TypeScript declaration for the decode function. Currently, the TypeScript type doesn't allow the optional second argument to be omitted, which can lead to linter complaints. To avoid these, one must explicitly pass `{stream: false}` even though it should be optional. It's a minor detail, but adjusting this could enhance usability.

Apart from this small point, the library is terrific and effectively addresses a significant need in React Native. Thanks again for your hard work and for making this public!

**Comment by maksimlya** [comment]
Hey @landabaso Thanks for your valuable input, I pushed code last night but wasn't sure if I did it correctly and only did quick local test, so I'm really glad that it works good for you! Also helped me to learn how to do the xcframework correctly. 👍  I will fix the linter later on.

**Comment by maksimlya** [comment]
@landabaso fixed lint in 0.1.12

**Comment by landabaso** [comment]
Great, thanks for the update! By the way, I noticed a small inconsistency in the README.md that might affect users who try to use the library as a polyfill. Currently, it shows:

```typescript
window.TextEncoder = TextEncoder;
window.TextDecoder = TextEncoder;
```

However, for React Native this should refer to `global`. Just a minor detail, but thought it would be worth mentioning!

**Comment by AndreiCalazans** [comment]
@landabaso do you use Flipper? 

I am having a ODR (One Definition Rule Violation) crash on iOS due to Folly that only happens if I add this fast-encoder. 

It's happening due to Flipper's Flipper-Folly but I'm confused to why this only happens when I add the fast-encoder lib. 


```
  [1] size=8 'folly::dynamic::TypeInfo<std::nullptr_t>::name' /Users/andreicalazans/redacted/mobile/src/packages/app/ios/Pods/RCT-Folly/folly/dynamic.cpp
  [2] size=8 'folly::dynamic::TypeInfo<std::nullptr_t>::name' /Users/andreicalazans/redacted/mobile/src/packages/app/ios/Pods/Flipper-Folly/folly/dynamic.cpp
These globals were registered at these points:
  [1]:
    #0 0x10dfbd920 in __asan_register_globals+0x98 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x15920)
    #1 0x10dff84f0 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*)+0x6c (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x504f0)
    #2 0x10dfbd870 in __asan_register_image_globals+0x30 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x15870)
    #3 0x10279a040 in asan.module_ctor+0x24 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Redacted:arm64+0x100006040)
    #4 0x10cfc00a4  (/usr/lib/dyld:arm64+0x140a4)
    #5 0x10cfe3a80  (/usr/lib/dyld:arm64+0x37a80)
    #6 0x10cfdb798  (/usr/lib/dyld:arm64+0x2f798)
    #7 0x10cfda46c  (/usr/lib/dyld:arm64+0x2e46c)
    #8 0x10cfda778  (/usr/lib/dyld:arm64+0x2e778)
    #9 0x10cfdce60  (/usr/lib/dyld:arm64+0x30e60)
    #10 0x10cfe37a0  (/usr/lib/dyld:arm64+0x377a0)
    #11 0x10cfbd064  (/usr/lib/dyld:arm64+0x11064)
    #12 0x10cfc267c  (/usr/lib/dyld:arm64+0x1667c)
    #13 0x10cfbd398  (/usr/lib/dyld:arm64+0x11398)
    #14 0x10cfc011c  (/usr/lib/dyld:arm64+0x1411c)
    #15 0x10cfbd4ec  (/usr/lib/dyld:arm64+0x114ec)
    #16 0x10cfd3ce0  (/usr/lib/dyld:arm64+0x27ce0)
    #17 0x10cfadfe4  (/usr/lib/dyld:arm64+0x1fe4)
    #18 0x10cfad394  (/usr/lib/dyld:arm64+0x1394)
    #19 0x10d0f79f4  (<unknown module>)
    #20 0x741800010d0f6458  (<unknown module>)
    #21 0x722d00010d0f5ed8  (<unknown module>)
    #22 0xf9627ffffffffffc  (<unknown module>)

  [2]:
    #0 0x10dfbd920 in __asan_register_globals+0x98 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x15920)
    #1 0x10dff84f0 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*)+0x6c (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x504f0)
    #2 0x10dfbd870 in __asan_register_image_globals+0x30 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Frameworks/libclang_rt.asan_iossim_dynamic.dylib:arm64+0x15870)
    #3 0x10279a040 in asan.module_ctor+0x24 (/Users/andreicalazans/Library/Developer/CoreSimulator/Devices/20D11FAB-E3B5-41F5-9833-0F41941E74BB/data/Containers/Bundle/Application/796353EB-E28C-4659-A387-D4868C509E91/Redacted.app/Redacted:arm64+0x100006040)
    #4 0x10cfc00a4  (/usr/lib/dyld:arm64+0x140a4)
    #5 0x10cfe3a80  (/usr/lib/dyld:arm64+0x37a80)
    #6 0x10cfdb798  (/usr/lib/dyld:arm64+0x2f798)
    #7 0x10cfda46c  (/usr/lib/dyld:arm64+0x2e46c)
    #8 0x10cfda778  (/usr/lib/dyld:arm64+0x2e778)
    #9 0x10cfdce60  (/usr/lib/dyld:arm64+0x30e60)
    #10 0x10cfe37a0  (/usr/lib/dyld:arm64+0x377a0)
    #11 0x10cfbd064  (/usr/lib/dyld:arm64+0x11064)
    #12 0x10cfc267c  (/usr/lib/dyld:arm64+0x1667c)
    #13 0x10cfbd398  (/usr/lib/dyld:arm64+0x11398)
    #14 0x10cfc011c  (/usr/lib/dyld:arm64+0x1411c)
    #15 0x10cfbd4ec  (/usr/lib/dyld:arm64+0x114ec)
    #16 0x10cfd3ce0  (/usr/lib/dyld:arm64+0x27ce0)
    #17 0x10cfadfe4  (/usr/lib/dyld:arm64+0x1fe4)
    #18 0x10cfad394  (/usr/lib/dyld:arm64+0x1394)
    #19 0x10d0f79f4  (<unknown module>)
    #20 0x741800010d0f6458  (<unknown module>)
    #21 0x722d00010d0f5ed8  (<unknown module>)
    #22 0xf9627ffffffffffc  (<unknown module>)
```

any ideas @maksimlya ?

Hey Oscar (@ospfranco), sorry to tag you like this but given your expertise would you have anything in mind?

**Comment by ospfranco** [comment]
Well, it seems both have loaded the same dylib somehow. I'm not sure why though, are you running this with the new arch? You can see on the podspec that when the new arch is enabled then RCTFolly is a declared dependency. I guess you can try removing it from there (as long as you are using flipper) and maybe it will work.

**Comment by AndreiCalazans** [comment]
It's not on the new arch. I also saw that depedency declaration due to the new arch and made sure to check, [that block](https://github.com/maksimlya/react-native-fast-encoder/blob/main/react-native-fast-encoder.podspec#L30) never runs.

**Comment by ospfranco** [comment]
The library is pretty bare bones, the entire code is just some C++ files, and it looks like it is a builder-bob generated repo. I doubt it is doing anything wrong. Sorry, no idea.

**Comment by maksimlya** [comment]
Not sure tbh, this lib was written based on https://github.com/jerson/react-native-fast-openpgp so most flags just went on just as is. I removed all flipper refernces tho, as latest rn does not uses it by default.
