### ISSUE TITLE
Is TextEncoder still needed with Hermes?

### ISSUE THREAD

**Issue by codybrouwers** [maksimlya/react-native-fast-text-encoder#2]
As mentioned in this comment:
- https://github.com/maksimlya/react-native-fast-encoder/issues/1#issuecomment-2053721513

Hermes recently added support for TextEncoder, but not TextDecoder. I wanted to get your perspective on only polyfiling TextDecoder and if you think there would be any issues with that?

Also, do you think in the instructions for polyfillng with this package it would be better to use the `polyfillGlobal` utility provided by react native?

```js
import { polyfillGlobal } from 'react-native/Libraries/Utilities/PolyfillFunctions';
import TextEncoder from 'react-native-fast-encoder';

polyfillGlobal('TextDecoder', () => TextEncoder);
polyfillGlobal('TextEncoder', () => TextEncoder);
```

**Comment by maksimlya** [comment]
@codybrouwers Hey, there shouldn't be any issues polyfilling only TextDecoder from my lib, but as far as I know, the latest hermes that includes TextEncoder is still not merged into react-native so I would check that before.
Polyfill - not sure, I just did something that worked for me. Is there any advantage of using this polyfillGlobal utility?

**Comment by codybrouwers** [comment]
Got it, thanks for the quick response! It looks like this commit as of React Native 0.74.1 does include TextEncoder: https://github.com/facebook/hermes/commit/7f9d9d5e44e2df5170f33d1604bea3b085f40e39

Yeah I'm not sure if using the built in polyfill is any better than just assigning to the global object but it is what React Native seems to use internally 🤷‍♂️:
https://github.com/facebook/react-native/blob/a881b51febd1fd809bc9d4fd368a1833f4c850c6/packages/react-native/Libraries/Core/polyfillPromise.js#L37

Will close this issue off though, thanks again for the great package! 🙏
